
@api= http://localhost:8000/equipos/create/


###
POST {{api}}
Content-Type: application/json

{
    "categoria_id": 1, 
    "nombre": "Osciloscopio",
    "descripcion": "Osciloscopio digital",
    "estado": "disponible"
}