# Generated by Django 5.2 on 2025-04-22 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Categorias_Equipos',
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('tipo_laboratorio', models.CharField(choices=[('electronica', 'Electrónica'), ('hardware', 'Hardware'), ('telecomunicaciones', 'Telecomunicaciones'), ('redes', 'Redes')], max_length=50)),
                ('capacidad', models.IntegerField()),
            ],
            options={
                'db_table': 'Laboratorios',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('tipo_usuario', models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor'), ('personal', 'Personal')], max_length=20)),
                ('numero_identificacion', models.CharField(max_length=20, unique=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_inventario', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En Uso'), ('en_mantenimiento', 'En Mantenimiento'), ('dado_de_baja', 'Dado de Baja')], default='disponible', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_adquisicion', models.DateField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='titulacion_proyect.categoriaequipo')),
                ('laboratorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='titulacion_proyect.laboratorio')),
            ],
            options={
                'db_table': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tecnico', models.CharField(blank=True, max_length=100)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titulacion_proyect.equipo')),
            ],
            options={
                'db_table': 'Mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='ReservaLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('proposito', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titulacion_proyect.laboratorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titulacion_proyect.usuario')),
            ],
            options={
                'db_table': 'Reservas_Laboratorio',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion_prevista', models.DateTimeField()),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('devuelto', 'Devuelto'), ('atrasado', 'Atrasado')], default='activo', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titulacion_proyect.equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titulacion_proyect.usuario')),
            ],
            options={
                'db_table': 'Prestamos',
            },
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='titulacion_proyect.usuario'),
        ),
    ]
